project:
  type: website
  output-dir: docs


website:
  title: "Atmospheric Environments"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      # - href: Modules/moduleInfo.qmd
      #   text: Lectures
    right:
      - icon: github
        href: https://github.com/GEOS270
        aria-label: Quarto GitHub

  sidebar:
    - title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - index.qmd
      - acknowledgement.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



