project:
  type: website
  output-dir: docs


website:
  title: "Atmospheric Environments"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures
      - href: LabAssignments.qmd
        text: Lab Assignments
    right:
      - icon: github
        href: https://github.com/GEOS200
        aria-label: Quarto GitHub

  sidebar:
    - title: "Syllabus"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - index.qmd
      - acknowledgement.qmd

      
    - title: "Lab Assignments"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - href: LabAssignments.qmd
        text: General Info
      - href: https://geos200.github.io/LabAssignments/1.html
        text: Lab 1
      - href: https://geos200.github.io/LabAssignments/2.html
        text: Lab 2
      - href: https://geos200.github.io/LabAssignments/3.html
        text: Lab 3
      - href: https://geos200.github.io/LabAssignments/4.html
        text: Lab 4
      - href: https://geos200.github.io/LabAssignments/5.html
        text: Lab 5
      - href: https://geos200.github.io/LabAssignments/6.html
        text: Lab 6
      - href: https://geos200.github.io/LabAssignments/7.html
        text: Lab 7

    - title: "Lectures"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
      - lectures.qmd
      - href: https://geos200.github.io/LectureSlides/Slides/1.html
        text: Lecture 1
      - href: https://geos200.github.io/LectureSlides/Slides/2.html
        text: Lecture 2
      - href: https://geos200.github.io/LectureSlides/Slides/3.html
        text: Lecture 3
      - href: https://geos200.github.io/LectureSlides/Slides/4.html
        text: Lecture 4
      - href: https://geos200.github.io/LectureSlides/Slides/5.html
        text: Lecture 5
      - href: https://geos200.github.io/LectureSlides/Slides/6.html
        text: Lecture 6
      - href: https://geos200.github.io/LectureSlides/Slides/7.html
        text: Lecture 7
      - href: https://geos200.github.io/LectureSlides/Slides/8.html
        text: Lecture 8
      - href: https://geos200.github.io/LectureSlides/Slides/9.html
        text: Lecture 9
      - href: https://geos200.github.io/LectureSlides/Slides/10.html
        text: Lecture 10
      - href: https://geos200.github.io/LectureSlides/Slides/11.html
        text: Lecture 11
      - href: https://geos200.github.io/LectureSlides/Slides/12.html
        text: Lecture 12
      - href: https://geos200.github.io/LectureSlides/Slides/13.html
        text: Lecture 13
      - href: https://geos200.github.io/LectureSlides/Slides/14.html
        text: Lecture 14
      - href: https://geos200.github.io/LectureSlides/Slides/15.html
        text: Lecture 15
      - href: https://geos200.github.io/LectureSlides/Slides/16.html
        text: Lecture 16
      - href: https://geos200.github.io/LectureSlides/Slides/17.html
        text: Lecture 17
      - href: https://geos200.github.io/LectureSlides/Slides/18.html
        text: Lecture 18
      - href: https://geos200.github.io/LectureSlides/Slides/19.html
        text: Lecture 19
      - href: https://geos200.github.io/LectureSlides/Slides/20.html
        text: Lecture 20
      - href: https://geos200.github.io/LectureSlides/Slides/21.html
        text: Lecture 21
      - href: https://geos200.github.io/LectureSlides/Slides/22.html
        text: Lecture 22
      - href: https://geos200.github.io/LectureSlides/Slides/23.html
        text: Lecture 23
      - href: https://geos200.github.io/LectureSlides/Slides/24.html
        text: Lecture 24
      - href: https://geos200.github.io/LectureSlides/Slides/25.html
        text: Lecture 25
      - href: https://geos200.github.io/LectureSlides/Slides/26.html
        text: Lecture 26
      - href: https://geos200.github.io/LectureSlides/Slides/27.html
        text: Lecture 27
      - href: https://geos200.github.io/LectureSlides/Slides/28.html
        text: Lecture 28
      - href: https://geos200.github.io/LectureSlides/Slides/29.html
        text: Lecture 29


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



